[package]
name = "rust2fun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rust2fun_laws = { path = "./laws" }

[features]
default = ["std"]

std = []

[workspace]
members = [
    "laws",
]
