name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build no_std
      run: cargo build --verbose --no-default-features
    - name: Build default
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
